[[rules]]
id = "generic-password-1"
description = "password"
regex = '''(?i)(?:password)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:{1,3}=|\|\|:|<=|=>|:|\?=)(?:'|\"|\s|=|\x60){0,5}([a-f0-9]{32})(?:['|\"|\n|\r|\s|\x60|;]|$)'''

[[rules]]
id = "generic-secret-1"
description = "apiKey"
regex = '''(?i)(?:apiKey)(?:[0-9a-z\-_\t .]{0,20})(?:[\s|']|[\s|"]){0,3}(?:=|>|:{1,3}=|\|\|:|<=|=>|:|\?=)(?:'|\"|\s|=|\x60){0,5}((?i)[a-z0-9-=+_]{0,36})(?:['|\"|\n|\r|\s|\x60|;]|$)'''
